/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teuria.songly;

import javax.swing.JOptionPane;

/**
 *
 * @author teuria
 */
public class MusicBankItem extends javax.swing.JPanel {
    
    private String path;
    private DeleteEvent delEvent;
    /**
     * Creates new form MusicBankItem
     */
    public MusicBankItem(String path, DeleteEvent evt) {
        initComponents();
        this.path = path;
        this.pathText.setText(path);
        this.delEvent = evt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathText = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 59));

        pathText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pathText.setText("Path");

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(delBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delBtn)
                    .addComponent(pathText))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // 0=yes, 1=no, 2=cancel
        int input = JOptionPane.showConfirmDialog(null, "Are you sure you want "
                + "to remove this directory?");
        
        // if the input is not 0 which is ok, then we do not proceed further
        if (input != 0) {
            return;
        }
        
        // lets fire up the delete event
        this.delEvent.run(this.path);
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel pathText;
    // End of variables declaration//GEN-END:variables
}

interface DeleteEvent {
    void run(String path);
}
