package com.teuria.songly;

import com.teuria.songly.events.MusicItemClickEvent;
import com.teuria.songly.models.Music;
import javax.swing.JFrame;


public class MusicItem extends javax.swing.JPanel {
    private Music music;
    private MusicItemClickEvent clickEvent;
    private JFrame main;
    
    /**
     * Creates new form MusicPanel
     */
    public MusicItem(JFrame main, Music music, MusicItemClickEvent evt) {
        initComponents();
        this.music = music;
        title.setText(music.getTitle());
        
        // if the music.getArtist doesn't exist, just set it to empty string
        if (music.getArtist().equals("null")) {
            artist.setText("");
        } else {
            artist.setText(music.getArtist());            
        }

        this.clickEvent = evt;
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        artist = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        addToPlaylistBtn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(32767, 51));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        title.setText("Title");

        artist.setText("Artist");

        icon.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.MUSIC_NOTE, 24, new java.awt.Color(255, 255, 255)));

        addToPlaylistBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.PLAYLIST_ADD, 24, new java.awt.Color(255, 255, 255)));
        addToPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPlaylistBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artist, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(addToPlaylistBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(artist))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon)
                            .addComponent(addToPlaylistBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        clickEvent.run(music);
    }//GEN-LAST:event_formMouseClicked

    private void addToPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPlaylistBtnActionPerformed
        // This will initialized a new dialog form called PlaylistForm
        // we passed around the main JFrame and the music model to this dialog
        PlaylistForm form = new PlaylistForm(main, music);
        form.setVisible(true);
    }//GEN-LAST:event_addToPlaylistBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToPlaylistBtn;
    private javax.swing.JLabel artist;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}