/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teuria.songly;

import com.teuria.songly.events.MusicBankItemDeleteEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author teuria
 */
public class MusicBankItem extends javax.swing.JPanel {
    
    private String path;
    private MusicBankItemDeleteEvent delEvent;
    /**
     * Creates new form MusicBankItem
     */
    public MusicBankItem(String path, MusicBankItemDeleteEvent evt) {
        initComponents();
        this.path = path;
        this.pathText.setText(path);
        this.delEvent = evt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathText = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 59));

        pathText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        pathText.setText("Path");

        delBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.DELETE, 24, new java.awt.Color(255, 255, 255)));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        refreshBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.REFRESH, 24, new java.awt.Color(255, 255, 255)));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshBtn)
                    .addComponent(delBtn)
                    .addComponent(pathText))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // 0=yes, 1=no, 2=cancel
        int input = JOptionPane.showConfirmDialog(null, "Are you sure you want "
                + "to remove this directory?");
        
        // if the input is 0 which is ok, then we do proceed further
        if (input == 0) {
            // lets fire up the delete event
            this.delEvent.run(this.path);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        AppState.index(path);
        AppState.save();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel pathText;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
