package com.teuria.songly;

import com.teuria.songly.models.Music;


public class MusicPanel extends javax.swing.JPanel {
    private Music music;
    /**
     * Creates new form MusicPanel
     */
    public MusicPanel(Music music) {
        initComponents();
        this.music = music;
        title.setText(music.getTitle());
        artist.setText(music.getArtist());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        artist = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 51));

        title.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        title.setText("Title");

        artist.setText("Artist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(artist))
                .addContainerGap(804, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(artist))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artist;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
