/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teuria.songly;

import com.teuria.songly.events.PlaylistItemClickEvent;
import com.teuria.songly.events.PlaylistItemDeleteEvent;
import com.teuria.songly.models.Playlist;
import javax.swing.JOptionPane;

/**
 *
 * @author teuria
 */
public class PlaylistItem extends javax.swing.JPanel {

    private Playlist playlist;
    private PlaylistItemClickEvent clickEvent;
    private PlaylistItemDeleteEvent delEvent;
    
    public PlaylistItem(
            Playlist playlist, 
            PlaylistItemClickEvent clickEvent,
            PlaylistItemDeleteEvent delEvent
    ) {
        initComponents();
        this.playlist = playlist;
        this.playlistTitle.setText(playlist.getTitle());
        this.clickEvent = clickEvent;
        this.delEvent = delEvent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playlistTitle = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(32767, 64));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        playlistTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        playlistTitle.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.PLAYLIST_PLAY, 24, new java.awt.Color(255, 255, 255)));
        playlistTitle.setText("Name");

        delBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.DELETE, 24, new java.awt.Color(255, 255, 255)));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playlistTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(delBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playlistTitle)
                    .addComponent(delBtn))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        clickEvent.run(playlist);
    }//GEN-LAST:event_formMouseClicked

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // 0=yes, 1=no, 2=cancel
        int input = JOptionPane.showConfirmDialog(null, "Are you sure you want "
                + "to remove this playlist?");
        
        // if the input is not 0 which is ok, then we do not proceed further
        if (input != 0) {
            return;
        }
        
        delEvent.run(playlist);
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel playlistTitle;
    // End of variables declaration//GEN-END:variables
}