package com.teuria.songly;

import com.teuria.songly.models.Music;
import com.teuria.songly.models.Playlist;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialOceanicTheme;

/**
 *
 * @author teuria
 */
public class SonglyForm extends javax.swing.JFrame {
    private final MediaPlayer player;
    private boolean isSeeking;
    public static SonglyForm instance;
    /**
     * Creates new form SonglyForm
     */
    public SonglyForm() {
        // load the data from the file
        AppState.load();
        setLocationByPlatform(true);
        initComponents();
        
        // we initialize our controller for playing music
        player = AppState.initPlayer();
        if (!player.isInitialized()) {
            // if the user does not have VLC installed (maybe they're on Linux)
            // we gave them an error message and let them install it.
            JOptionPane.showMessageDialog(this,
                "No VLC is installed, media player will not work!",
                "ERROR.",
                JOptionPane.ERROR_MESSAGE);
        }
        
        // we set up the event for changing music information for the control
        // title below..
        player.addSelectEvent(this::onPlayMusic);
        player.addTimeEvent(this::onTimeChanged);
        
        // we refresh the playlist here, so it will render all the item
        refreshPlaylist();
        instance = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        destinationLabel = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        songListScroll = new javax.swing.JScrollPane();
        songListPanel = new javax.swing.JPanel();
        playlistPanel = new javax.swing.JPanel();
        playlistScroll = new javax.swing.JScrollPane();
        playlistItemList = new javax.swing.JPanel();
        addPlaylistBtn = new javax.swing.JButton();
        addPlaylistField = new javax.swing.JTextField();
        musicBankPanel1 = new com.teuria.songly.MusicBankPanel();
        nextBtn = new javax.swing.JButton();
        playPauseBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        songTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Songly");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Songly.png"))); // NOI18N
        jLabel1.setText("SONGLY");

        slider.setValue(0);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sliderMouseReleased(evt);
            }
        });

        destinationLabel.setText("0:00");

        currentLabel.setText("0:00");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        songListScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        songListPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 72, 123)));
        songListPanel.setMaximumSize(new java.awt.Dimension(32810, 164060));
        songListPanel.setLayout(new javax.swing.BoxLayout(songListPanel, javax.swing.BoxLayout.Y_AXIS));
        songListScroll.setViewportView(songListPanel);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(songListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(songListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", home);

        playlistScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        playlistItemList.setLayout(new javax.swing.BoxLayout(playlistItemList, javax.swing.BoxLayout.Y_AXIS));
        playlistScroll.setViewportView(playlistItemList);

        addPlaylistBtn.setText("+ Add");
        addPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlaylistBtnActionPerformed(evt);
            }
        });

        addPlaylistField.setToolTipText("Playlist Name");

        javax.swing.GroupLayout playlistPanelLayout = new javax.swing.GroupLayout(playlistPanel);
        playlistPanel.setLayout(playlistPanelLayout);
        playlistPanelLayout.setHorizontalGroup(
            playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistPanelLayout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(addPlaylistField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPlaylistBtn)
                .addContainerGap())
            .addGroup(playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(playlistPanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(playlistScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        playlistPanelLayout.setVerticalGroup(
            playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlaylistBtn)
                    .addComponent(addPlaylistField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(448, Short.MAX_VALUE))
            .addGroup(playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(playlistPanelLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(playlistScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Playlist", playlistPanel);
        jTabbedPane1.addTab("Library", musicBankPanel1);

        nextBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.SKIP_NEXT, 24, new java.awt.Color(255, 255, 255)));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        playPauseBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.PLAY_ARROW, 24, new java.awt.Color(255, 255, 255)));
        playPauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPauseBtnActionPerformed(evt);
            }
        });

        previousBtn.setIcon(jiconfont.swing.IconFontSwing.buildIcon(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.SKIP_PREVIOUS, 24, new java.awt.Color(255, 255, 255)));
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        songTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(currentLabel)
                                        .addGap(343, 343, 343)
                                        .addComponent(previousBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(playPauseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(destinationLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(songTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(523, 523, 523)
                .addComponent(songTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousBtn)
                    .addComponent(playPauseBtn)
                    .addComponent(nextBtn)
                    .addComponent(currentLabel)
                    .addComponent(destinationLabel))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(124, Short.MAX_VALUE)))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        player.previous();
    }//GEN-LAST:event_previousBtnActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        refresh(); // refresh whenever changing the tab, so the music list is
        // always updated
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void addPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlaylistBtnActionPerformed
        String name = addPlaylistField.getText();
        if (name.isBlank()) {
            JOptionPane.showMessageDialog(this,
                "Playlist field name is empty.",
                "ERROR.",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (AppState.hasPlaylist(name)) {
            JOptionPane.showMessageDialog(this,
                "Playlist with this name already exists.",
                "ERROR.",
                JOptionPane.ERROR_MESSAGE);
            return;      
        }
        
        Playlist playlist = new Playlist(name, 0);
        AppState.addPlaylist(playlist);
        AppState.save();
        refreshPlaylist();
        addPlaylistField.setText("");
    }//GEN-LAST:event_addPlaylistBtnActionPerformed

    private void playPauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPauseBtnActionPerformed
        if (player.isPaused()) {
            playPauseBtn.setIcon(IconFontSwing.buildIcon(
                    GoogleMaterialDesignIcons.PAUSE, 24, 
                    new java.awt.Color(255, 255, 255)));
            player.play();
        } else {
            playPauseBtn.setIcon(IconFontSwing.buildIcon(
                    GoogleMaterialDesignIcons.PLAY_ARROW, 24, 
                    new java.awt.Color(255, 255, 255)));
            player.pause();
        }
    }//GEN-LAST:event_playPauseBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        player.next();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        if (slider.getValueIsAdjusting() || !isSeeking) {
            return;
        }
        
        SwingUtilities.invokeLater(() -> {
            player.seek(slider.getValue());
        });
    }//GEN-LAST:event_sliderStateChanged

    private void sliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMousePressed
        isSeeking = true;
        player.pause();
    }//GEN-LAST:event_sliderMousePressed

    private void sliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseReleased
        isSeeking = false;
        player.play();
    }//GEN-LAST:event_sliderMouseReleased

    private void refreshPlaylist() {
        // remove all items in the playlist panel
        // we will then, revalidate it so it will actually be removed
        // then repaint to rerender the items that they're actually gone
        playlistItemList.removeAll();
        playlistItemList.revalidate();
        playlistItemList.repaint();
        
        // we will then initialize and add all of the playlist once again
        for (Playlist playlist : AppState.getPlaylists()) {
            PlaylistItem item = new PlaylistItem(playlist, 
            // setup click event
            (pl) -> {
                playlistItemList.removeAll();
                playlistItemList.revalidate();
                playlistItemList.repaint();
                
                // initialize the container, as well as the button
                JPanel container = new JPanel();
                container.setLayout(
                        new BoxLayout(container, BoxLayout.LINE_AXIS));
                
                // we need to set it into a same size as the playlist item
                // was
                container.setSize(764, 53);
                container.setMaximumSize(new Dimension(32767, 53));
                container.setPreferredSize(new Dimension(764, 53));
                
                // set the title based on the playlist name, and set its icon
                JButton backBtn = new JButton(pl.getTitle());
                
                backBtn.setIcon(IconFontSwing.buildIcon(
                        GoogleMaterialDesignIcons.KEYBOARD_ARROW_LEFT,
                        24,
                        new java.awt.Color(255, 255, 255)
                ));
                
                // put it to the left
                backBtn.setAlignmentX(0);
                
                // setup the click event
                backBtn.addActionListener((evt) -> {
                    // we'll just reset everything to go back
                    refreshPlaylist();
                });
                // add it to the jframe now
                container.add(backBtn);
                playlistItemList.add(container);
                
                // add all the rest of the music in the playlist
                for (Music music : pl.getSongs()) {
                    MusicItem panel = new MusicItem(
                        this, music, (m) -> {
                            player.setPlaylist(pl);
                            onClickedMusicPanel(m);
                        });
                    playlistItemList.add(panel);
                }
            },
            // setup delete event
            (pl) -> {
                AppState.removePlaylist(pl);
                AppState.save();
                refreshPlaylist();
            },
            (pl, name) -> {
                AppState.renamePlaylist(pl, name);
                AppState.save();
                refreshPlaylist();
            });
            
            // add the playlist to the lists
            playlistItemList.add(item);
        }
    }
    
    private void refresh() {
        // just for optimization, so we only refresh when is needed
        // (after adding or removing music as such)
        if (AppState.isRendered()) {
            return;
        }
        
        songListPanel.removeAll();
        songListPanel.revalidate();
        songListPanel.repaint();
        
        for (Music music : AppState.getMusics()) {
            MusicItem panel = new MusicItem(
                this, music, (m) -> {
                    player.setPlaylist(null);
                    onClickedMusicPanel(m);
                });
            songListPanel.add(panel);
        }
    }
    
    // this function is called via the event when media player changed
    // the music
    private void onPlayMusic(Music music) {
        // this just change the music information from the control
        if (!music.getArtist().equals("null")) {
            songTitle.setText(music.getTitle() + " - " + music.getArtist());            
        } else {
            songTitle.setText(music.getTitle());
        }

        destinationLabel.setText(player.getTimeEndFormatted());
        slider.setMaximum((int)player.getTimeEnd());
    }
    
    private void onTimeChanged(long time) {
        currentLabel.setText(player.getCurrentTimeFormatted());
        slider.setValue((int)player.getCurrentTime());
    }
    
    private void onClickedMusicPanel(Music music) {
        // this will change the icon of the pause/play on the controls
        // and then select and play the song from a media player
        playPauseBtn.setIcon(IconFontSwing.buildIcon(
                GoogleMaterialDesignIcons.PAUSE, 24, 
                new java.awt.Color(255, 255, 255)));
        player.selectAndPlay(music);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

            javax.swing.UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialOceanicTheme()));
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SonglyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SonglyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SonglyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SonglyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        IconFontSwing.register(GoogleMaterialDesignIcons.getIconFont());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SonglyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlaylistBtn;
    private javax.swing.JTextField addPlaylistField;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.teuria.songly.MusicBankPanel musicBankPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton playPauseBtn;
    private javax.swing.JPanel playlistItemList;
    private javax.swing.JPanel playlistPanel;
    private javax.swing.JScrollPane playlistScroll;
    private javax.swing.JButton previousBtn;
    private javax.swing.JSlider slider;
    private javax.swing.JPanel songListPanel;
    private javax.swing.JScrollPane songListScroll;
    private javax.swing.JLabel songTitle;
    // End of variables declaration//GEN-END:variables
}